### ISSUE TITLE
Tab indentation (and even 4 indent spaces) in templates not works and breaks the app

### ISSUE THREAD

**Issue by voronianski** [STRd6/hamlet#12]
It looks weird.. I prefer tabs indentation though I can switch to spaces for a while.. but stricted only for 2 spaces?? Are you serious?

```haml
%h2 Todos
%input(type="text" @value placeholder="What needs to be done?" onkeydown=@add)

%ul
    -each @todos, ->
        %li= @description
```

This brings such crazy error:

```bash
TypeError: Cannot read property 'children' of undefined
  at Object.extend.appendChild (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp-hamlet-compile/node_modules/hamlet-compiler/node_modules/hamlet-parser/dist/main.js:1:1282)
  at Object.extend.append (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp-hamlet-compile/node_modules/hamlet-compiler/node_modules/hamlet-parser/dist/main.js:1:1063)
  at Object.anonymous (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp-hamlet-compile/node_modules/hamlet-compiler/node_modules/hamlet-parser/dist/parser.js:1:1488)
  at Object.parse (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp-hamlet-compile/node_modules/hamlet-compiler/node_modules/hamlet-parser/dist/parser.js:1:8141)
  at Object.extend.parse (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp-hamlet-compile/node_modules/hamlet-compiler/node_modules/hamlet-parser/dist/main.js:1:603)
  at Transform._transform (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp-hamlet-compile/index.js:33:55)
  at Transform._read (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp-hamlet-compile/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at Transform._write (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp-hamlet-compile/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp-hamlet-compile/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:238:10)
  at writeOrBuffer (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp-hamlet-compile/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:228:5)
  at Transform.Writable.write (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp-hamlet-compile/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:195:11)
  at write (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:605:24)
  at flow (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:614:7)
  at Transform.pipeOnReadable (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:646:5)
  at Transform.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:430:10)
  at emitReadable (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:426:5)
  at readableAddChunk (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at Transform.Readable.push (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at Transform.push (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at Transform.noop [as _transform] (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/through2.js:8:3)
  at Transform._read (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at Transform._write (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:238:10)
  at writeOrBuffer (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:228:5)
  at Transform.Writable.write (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:195:11)
  at write (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:605:24)
  at flow (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:614:7)
  at Transform.pipeOnReadable (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:646:5)
  at Transform.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:430:10)
  at emitReadable (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:426:5)
  at readableAddChunk (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at Transform.Readable.push (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at Transform.push (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at /Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
  at evalmachine.<anonymous>:266:14
  at /Users/dmitri/github/hamlet-boilerplate/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:102:5
  at Object.oncomplete (evalmachine.<anonymous>:107:15)
```

**Comment by STRd6** [comment]
Fixed
